### PR TITLE
Added @NonNull and @Nullable many places

### PR DESCRIPTION
**Pull request by paulirotta**
Adding annotations for more strict null checking in the IDE, thread safety and overriding class safety

Renamed package for the example to match the library (.bignerdranch.)
Added @UiThread many places to help the compiler indicate non-thread-safe usage at an early phase (fail fast)
Added @CallSuper or final to many extendable class methods to more safe extension
Updating versioning to 2.2.0

### CODE REVIEW

**Comment by paul-turner** [comment]
Thank you for taking the time to make this PR. We are currently in between releases and would love to have your changes on the `dev-3.0.0` branch instead of `master`. Would it be possible for you to base your changes off of `dev-3.0.0`? You'll find that the package change is already there for that one. Hopefully this will help us get a release quicker when we merge with master soon.

Thanks again for the help!

**Comment by paulirotta** [comment]
Sure, I'll duplicate these against dev-3.0.0 as soon as possible.

**Comment by paul-turner** [comment]
Thank you, appreciate the help very much. Might want to wait until after
Wednesday as there are two PRS in the pipeline that modify some method
names, just to save some trouble/duplicate work.

**Comment by paulirotta** [comment]
You're welcome. I saw there might be some collisions with other PRs. Nice to see the library is active.

A request for the future direction would be more strict type safety enforcement.

**Comment by paul-turner** [comment]
#263 might be just what you want then. If you have any other ideas, feel free to drop in an issue :)

**Pull request closed without merging**
