### PR TITLE
Adding and replacing items through adapter.

### PR DESCRIPTION
**Pull request by DarekDeo**
Added 2 methods that allow dynamically adding items. Tested only replace method, but add should do fine too.

Tested replace method using EventBus and RecyclerView in separate Fragment from MainActivity in my private work project which I can't share. List gets updated greatfuly when EventBus sends new items. :)

### CODE REVIEW

**Comment by paul-turner** [comment]
At first look this doesn't seem to account for if there are already expanded items in the list at the time of adding. Do you know if that's the case? Seems like anything that is expanded would collapse when I use the method to add items because the helperitem list is regenerated from scratch.

**Comment by DarekDeo** [comment]
Set in Your ParentObject that it is initialy expanded, that is something was user of library can implement, then ExpandableRecyclerAdapterHelper will check if parentObject.isInitiallyExpanded() and expand it after filling the list again.

**Comment by paul-turner** [comment]
Unfortunately I don't think it should be the job of the user of the library to keep track of runtime changes. isInitiallyExpanded is meant to just give the initial state, if a user taps on rows to expand/collapse this runtime state should be preserved when adding items automatically.

We should be tackling the editing of items in the next day or so if you think this is more than you need for your use case. I do appreciate the contribution though.

**Comment by DarekDeo** [comment]
Still working on it, not updating ID's yet so after screen orientation change for example Bundle still loads old IDs and expand wrong lists, just noticed it after commit. Will fix it.

**Comment by DarekDeo** [comment]
Will fix it tomorrow morning, Bundle refresh wrong items ONLY on the first time refresh for some unknown to me reason - after that each next refresh shows correctly expanded items. As I said: tomorrow I will look into it again with small help, today I might be just to tired to see some funny bug...

**Comment by paul-turner** [comment]
No problem. I'll note that currently the current implementation of id generation is simply based on position in the list, so if items are changing it is not likely that the correct state is being restored to the correct position (as the id's will match to the wrong object).

I'll be starting on smaller changes with adding/removing individual items which may clash with these changes. I'll try to keep these changes in mind as I work through it.

**Comment by DarekDeo** [comment]
It was small fix in AdapterHelper, I've also refactored my stupidity there, slightly less code now. :) Works like a charm. Let me know if you notice anything else.

ps haven't said thanks for this nice library yet - thanks!

**Comment by DarekDeo** [comment]
One more thing to mention, for testing I have added button to add crimes in FragmentCrimeList. It allows to add 1 crime, locally I have tested if it will work fine while adding more items at once - it works ok, expanded state is saved correctly.

**Comment by DarekDeo** [comment]
For some reason putAll did not put the elements into mStableIdMaps, that's weird. I've decided to generate all stableIdmaps when new elements is added, just like in constructor and replace method.

Additionaly in CrimeListFragment example I've moved creating adapter and adapter's onRestoreInstanceState to onCreate method, that's followed by setRetainInstance(true). This means fragment won't get recreated each time orientation will change, otherwise added items in example list would get messy (duplicate child elements). To show added elements when activity gets destroyed elements needs to be saved into Bundle, when onCreate would be called new elements would need to be added to "generateCrimes". I am not doing this in example, but it is normal Android behavior.

**Comment by paul-turner** [comment]
@DarekDeo master changed a little bit since this PR got started, we removed stableId's in order to make addition/removal more possible. I'd love for you to take a look at #74 and tell me what you think about it.

**Comment by varunpdr** [comment]
how to delete child Items from list..and after deleting..child items by notifychilditemremoved...it also delete parent item with same position what the hell is this..

**Comment by paul-turner** [comment]
@varunpdr Hi there,
If you could open a new issue with the details of your problem. Code to recreate the issue will go a long way in helping us fix the problem for you as we have plenty of sample code showing `notifychilditemremoved` is working as intended.

Thanks!

**Comment by varunpdr** [comment]
Hi, I have used notifyChildItemRemoved method for parent having 3 children. After swipe removed i call notifychilditemremoved for that particular child..The child get deletes temporarily from list and when i touch back to its parent..the parent next to current  parent get removes...and on clicking the current parent again child again appears...This is troubling me a..lot....   And Do i need to do any more calls after notifychilditemremoved...so that it could work..or can you show me the code..where this functionaility is being called. Thanks in advance..

**Comment by paul-turner** [comment]
@varunpdr 
Here is a sample:
https://github.com/bignerdranch/expandable-recycler-view/blob/master/sampleapp/src/main/java/com/ryanbrooks/expandablerecyclerviewsample/linear/horizontal/HorizontalLinearRecyclerViewSampleActivity.java#L292

Let me know if that helps, if not please open a new issue to continue discussion.

**Pull request closed without merging**
